# Generated by Django 2.1.5 on 2019-02-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=13, verbose_name='CPF')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('telefone', models.CharField(max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Clente',
                'verbose_name_plural': 'Clentes',
            },
        ),
    ]
