# Generated by Django 2.1.5 on 2019-03-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Profissional')),
                ('telefone', models.CharField(blank=True, max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissional',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Seviço')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('pagamento', models.CharField(blank=True, choices=[('AD', 'Avista Dinheiro'), ('CD', 'Cartão Debito'), ('CC', 'Cartão Credito')], max_length=2, verbose_name='Pagamento')),
                ('executante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profissional.Prof')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
