# Generated by Django 2.1.5 on 2019-03-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='executante',
        ),
    ]
