# Generated by Django 2.1.5 on 2019-03-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0002_remove_service_executante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='preco',
        ),
    ]
