# Generated by Django 2.1.5 on 2019-03-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0003_remove_service_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('AD', 'Dinheiro'), ('CD', 'Cartão Debito'), ('CC', 'Cartão Credito')], max_length=2, verbose_name='Pagamento'),
        ),
    ]
